Name:           ros-melodic-tuw-nav-msgs
Version:        0.0.9
Release:        0%{?dist}
Summary:        ROS tuw_nav_msgs package

Group:          Development/Libraries
License:        BSD
Source0:        %{name}-%{version}.tar.gz

BuildArch:      noarch

Requires:       ros-melodic-geometry-msgs
Requires:       ros-melodic-message-runtime
Requires:       ros-melodic-nav-msgs
Requires:       ros-melodic-roscpp
Requires:       ros-melodic-rospy
Requires:       ros-melodic-std-msgs
Requires:       ros-melodic-tf
Requires:       ros-melodic-tuw-geometry-msgs
BuildRequires:  ros-melodic-catkin
BuildRequires:  ros-melodic-geometry-msgs
BuildRequires:  ros-melodic-message-generation
BuildRequires:  ros-melodic-nav-msgs
BuildRequires:  ros-melodic-roscpp
BuildRequires:  ros-melodic-rospy
BuildRequires:  ros-melodic-std-msgs
BuildRequires:  ros-melodic-tf
BuildRequires:  ros-melodic-tuw-geometry-msgs

%description
The tuw_nav_msgs package

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/melodic

%changelog
* Wed Sep 12 2018 George Todoran <george.todoran@tuwien.ac.at> - 0.0.9-0
- Autogenerated by Bloom

* Fri Jul 13 2018 George Todoran <george.todoran@tuwien.ac.at> - 0.0.8-0
- Autogenerated by Bloom

* Tue Jul 03 2018 George Todoran <george.todoran@tuwien.ac.at> - 0.0.7-2
- Autogenerated by Bloom

* Tue Jul 03 2018 George Todoran <george.todoran@tuwien.ac.at> - 0.0.7-1
- Autogenerated by Bloom

* Wed May 30 2018 George Todoran <george.todoran@tuwien.ac.at> - 0.0.7-0
- Autogenerated by Bloom

* Thu May 03 2018 George Todoran <george.todoran@tuwien.ac.at> - 0.0.6-0
- Autogenerated by Bloom

* Thu May 03 2018 George Todoran <george.todoran@tuwien.ac.at> - 0.0.5-0
- Autogenerated by Bloom

